# Generated by Django 4.1.7 on 2023-02-28 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_language_remove_snippet_lang_alter_comment_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='lang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='MainApp.language'),
        ),
    ]
